### ISSUE TITLE
Discrepancy in UGens name

### ISSUE THREAD

**Issue by ghost** [sensestage/bela-remote#2]
Named In in bela files, Input in Extensions on main computer.

/usr/local/share/SuperCollider/SCClassLibrary/Common/Audio/bela/BELAUGens.sc

AnalogIn : UGen
AnalogOut : UGen

/home/ulrich/.local/share/SuperCollider/Extensions/bela-remote/Classes/BELAUGens.sc

AnalogInput : UGen
AnalogOutput : UGen

**Comment by sensestage** [comment]
Fixed now; this was the same issue as #1.
We changed the names for consistency with In / Out UGens during the Bela workshop at STEIM.
