### ISSUE TITLE
ERROR: There is a discrepancy.

### ISSUE THREAD

**Issue by 5InE-W** [sensestage/bela-remote#3]
Hallo, 
i try to add this extensions to my SuperCollider, just did what needs to be done as written by the README. But as i complete the last step - "Reboot interpreter", it show me an error:
`ERROR: There is a discrepancy.
numClassDeps 2118   gNumClasses 4226`
could anyone help me out, what the problem could be?
Best,

**Comment by raimund** [comment]
did you found a solution for this?

**Comment by sensestage** [comment]
Since I made this repository, the Bela classes for SuperCollider have been merged in the main source. So no need to separately install these anymore. I will adjust the README
